instagram/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^member/', include('member.urls', namespace='member')),







]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

instagram/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<author_pk>\d+)/(?P<comment_pk>\d+)/comment/delete/$', views.comment_delete, name='comment_delete'),
    url(r'^(?P<author_pk>\d+)/(?P<post_pk>\d+)/post/delete/$', views.post_delete, name='post_delete'),
]

instagram/post/models.py
from django.conf import settings
from django.db import models


# Create your models here.

class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(author=None)


class Post(models.Model):
    # author = models.ForeignKey(User)
    # 직접 유저 모델을 불러왔을 때랑 어떤 이점이?
    # 이름이 바뀌어도 되고 기본모델이건 커스텀모델이건 상관없음
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    photo = models.ImageField(upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)

    objects = PostManager()

    class Meta:
        ordering = ['-created_at']


class PostComment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    # related_name을 적으면 역참조 가능
    # post.postcomment_set.all의 정참조 접근을
    # post.comments.all 로 대신하여 역참조 할 수 있음
    post = models.ForeignKey(Post, related_name="comments")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 가장 나중에 달린 Comment가 가장 나중에 오도록 ordering설정
        ordering = ['created_at']

instagram/post/forms.py
from django import forms

__all__ = (
    'PostForm',
    'CommentForm',
)


class PostForm(forms.Form):
    photo = forms.ImageField(
        required=True,
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            }
        ),
    )
    # text를 받을 수 있는 필드 추가
    text = forms.CharField(
        max_length=5,

    )

    def clean_text(self):
        data = self.cleaned_data['text']
        if data != data.upper():
            raise forms.ValidationError('All text must uppercase!')
        return data


class CommentForm(forms.Form):
    content = forms.CharField(
        # 엔터 허용 widget 옵션
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        ),
    )

instagram/post/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect

from post.forms import PostForm, CommentForm
from .models import Post, PostComment


def post_list(request):
    posts = Post.objects.exclude(author__isnull=True)
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form': comment_form,
    }

    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    # post = Post.objects.get(pk=post_pk)

    # Post 에서 pk값을 찾고 없으면 404 error
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()

    context = {
        'post': post,
        'comment_form': comment_form,
    }

    return render(request, 'post/post_detail.html', context)


def post_create(request):
    # 로그인한 유저만 접근 및 POST요청 가능
    if not request.user.is_authenticated:
        return redirect('member:login')

    if request.method == 'POST':
        # POST요청의 경우 PostForm인스턴스 생성과정에서 request.POST, request.FILES를 사용
        form = PostForm(request.POST, request.FILES)
        # 만약 form이 유효성검사를 통과헀다면 true리턴
        if form.is_valid():
            # 유효할 경우 Post인스턴스를 생성 및 저장
            post = Post.objects.create(
                author=request.user,
                photo=form.cleaned_data['photo'],
            )
            return redirect('post:post_list')

    else:
        # GET 요청의 경우 빈 PostForm인스턴스를 생성해서 템플릿에 전달
        form = PostForm()

    # GET 요청에선 이 부분이 무조건 실행
    # POST 요청에선 form.is_valid()를 통과하지 못하면 이 부분이 실행
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


def comment_create(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('member:login')
    # URL get parameter로 온 'post_pk'에 해당하는
    # Post instacne를 'post'변수에 할당
    # 찾지못하면 404Error를 브라우저에 리턴
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        # 데이터가 바인딩된 CommentForm인스턴스를 form에 할당
        form = CommentForm(request.POST)
        # 유효성 검증
        if form.is_valid():
            # 통과한 경우, Post에 해당하는 Comment 인스턴스 생성
            PostComment.objects.create(
                author=request.user,
                post=post,
                content=form.cleaned_data['content']
            )

            # post_list에서 오는 요청 처리
            next = request.GET.get('next')
            print(next)

            if next:
                return redirect(next)
            # 생성 후 Post의 detail화면으로 이동
            return redirect('post:post_detail', post_pk=post_pk)


def post_delete(request, author_pk, post_pk):
    if request.user.is_authenticated:
        post = Post.objects.filter(author_id=author_pk).get(pk=post_pk)
        post.delete()
        return redirect('post:post_list')
    else:
        raise PermissionDenied('접근 권한이 없습니다.')


def comment_delete(request, author_pk, comment_pk):
    if request.user.is_authenticated:
        comment = PostComment.objects.filter(author_id=author_pk).get(pk=comment_pk)
        comment.delete()
    return redirect('post:post_list')

instagram/templates/include/form-horizontal.html
    <form action="" method="POST" class="form-horizontal">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group {% if field.errors %} has-error{% endif %}">
            <lable for="{{ field.auto_id }}"
                   class="col-xs-2 control-label">
                {{ field.label }}
            </lable>
            <div class="col-xs-10">
                {{ field }}
                {% if field.errors %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endif %}
            </div>

        </div>
        {% endfor %}

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <button class="btn btn-primary btn-block">{{ submit_text }}</button>
    </form>

instagram/templates/include/post.html
<div class="body-content">

    <form
            action="{% url 'post:comment_create' post_pk=post.pk %}{{ submit_text }}"
            method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <button class="btn btn-primary btn-block">댓글달기</button>
    </form>


    <ul id="post-comments-{{ post.pk }}">

            {% for comment in post.comments.all %}
            <li>{{comment.author }} : {{ comment.content }}</li>

                {% if user.pk == comment.author.pk %}
                <form
                action="{% url 'post:comment_delete' author_pk=comment.author.pk comment_pk=comment.pk %}"
                method="POST">
                    {% csrf_token %}
                    <button class="btn btn-xs btn-primary">댓글삭제</button>
                {% endif %}
                </form>

            {% endfor %}
    </ul>
</div>